### ISSUE TITLE
Iphone XR... iOS 14.2 SSL KILL SWITCH not working!

### ISSUE THREAD

**Issue by iamsidharthbnair** [nabla-c0d3/ssl-kill-switch2#102]
Installed the 0.14 deb file but the SSL KILL SWITCH is not reflecting under the setting menu

**Comment by iamsidharthbnair** [comment]
Re-checked, latest update is working. Thanks

**Comment by patrickbdev** [comment]
How did you solve this @sidh104 ?

**Comment by JobberRT** [comment]
Sorry for re-open this issue, but hey @sidh104 can you explain how you get SSL KILL SWITCH shown up in the setting menu?
My device:
Iphone X with IOS14.7.1 (checkra1n 0.12.4-beta jailbreak)

Cydia Substrate 0.9.7113
Debain Packager 1.19.7-2
PreferenceLoader 2.2.6
SSL KILL SWITCH 2 0.14-3+debug

Already updated all Cydia application

**Comment by ptrkstr** [comment]
> Sorry for re-open this issue, but hey @sidh104 can you explain how you get SSL KILL SWITCH shown up in the setting menu?
> 
> My device:
> 
> Iphone X with IOS14.7.1 (checkra1n 0.12.4-beta jailbreak)
> 
> 
> 
> Cydia Substrate 0.9.7113
> 
> Debain Packager 1.19.7-2
> 
> PreferenceLoader 2.2.6
> 
> SSL KILL SWITCH 2 0.14-3+debug
> 
> 
> 
> Already updated all Cydia application

Have you tried force closing the settings app?

**Comment by JobberRT** [comment]
> > Sorry for re-open this issue, but hey @sidh104 can you explain how you get SSL KILL SWITCH shown up in the setting menu?
> > My device:
> > Iphone X with IOS14.7.1 (checkra1n 0.12.4-beta jailbreak)
> > Cydia Substrate 0.9.7113
> > Debain Packager 1.19.7-2
> > PreferenceLoader 2.2.6
> > SSL KILL SWITCH 2 0.14-3+debug
> > Already updated all Cydia application
> 
> Have you tried force closing the settings app?

sorry for replying late, things being too busy lately.
i try to do a system reset, then it worked, same steps but work.. thanks for helping me
