### ISSUE TITLE
not work in ip11,14.7.1 ,unc0ver

### ISSUE THREAD

**Issue by coolkidhai** [nabla-c0d3/ssl-kill-switch2#105]
not work in my ip11
version:14.7.1
unc0ver
it work well in my ipx ,14.4  ,checkra1n

**Comment by coolkidhai** [comment]
it's seems not work on system apps.not injected

**Comment by 1trackprojects1** [comment]
im having problems as well with unc0ver and 14.1

**Comment by coolkidhai** [comment]
> im having problems as well with unc0ver and 14.1


it's the problem of arm64e.
check this issues.
https://github.com/theos/theos/issues/563
you can choose target ios version >14.1,and compile with arm64e.it's work for me .

**Comment by JonathanJonathanJonathan** [comment]
@coolkidhai is it possible to share your .deb file? :)
