### ISSUE TITLE
Doesn't work on iOS 9.0.2

### ISSUE THREAD

**Issue by steelzeh** [nabla-c0d3/ssl-kill-switch2#11]
Doesn't disable any of the HTTPS calls.
Everything still happens with HTTPS and no SSL is disabled.

Downloaded your release from 25 days ago, installed it resprung my device, and nothing.
Tried restarting didn't help.

Thought it may have something do with appslicing, tried downloading apps from iTunes didn't help.

**Comment by nabla-c0d3** [comment]
Please try the latest release and re-open an issue (with information such as which App you were trying to proxy) if it is still not working. Thanks!
