### ISSUE TITLE
Not working with AppleID login，IOS13.2.3

### ISSUE THREAD

**Issue by Javer14551** [nabla-c0d3/ssl-kill-switch2#113]
iphone：IOS 13.2.3
jailbreak devices：check1n
Install ssl - kill - switch 2 correctly，Unable to log in to Appleid in Appstore，Ask for help to solve this problem, thank you

**Comment by senolatac** [comment]
https://nabla-c0d3.github.io/blog/2013/08/20/intercepting-the-app-stores-traffic-on-ios/
