### ISSUE TITLE
How to install ssl-kill-switch2 on iOS 15.4 Dopamine rootless jailbreak

### ISSUE THREAD

**Issue by gabrielwinter08** [nabla-c0d3/ssl-kill-switch2#118]
Hey my device is a iphone 13 pro iOS 15.4, i can't even add https://julioverne.github.io/ repo to install kill switch. I get this error: 

Error: Didn't find architectures
DPKGArchitecture() in https://julioverne.github.io/Release
Error: Could not find release file for https://julioverne.github.io/

**Comment by B1tBreaker** [comment]
Same problem here.

**Comment by novitae** [comment]
Install it manually, use dpkg

**Comment by stevejubx** [comment]
I recommend trying SSL Kill Switch 3 (https://github.com/NyaMisty/ssl-kill-switch3), as it now supports rootless jailbreak.

**Comment by Xiao7XS** [comment]
> 我建议尝试 SSL Kill Switch 3 ( https://github.com/NyaMisty/ssl-kill-switch3 )，因为它现在支持无根越狱。

Hello, does it support ios 16.6 iphone8puls?

**Comment by venkatrajkannan** [comment]
If you don't have Cydia, Then we can use SSLKillSwitch3 https://github.com/NyaMisty/ssl-kill-switch3/releases for Dopamine. Just download .deb file and install it using Filzila or any other method and restart your spring board, it will be showing in your iPhone Settings.
