### ISSUE TITLE
iOS 10.1(.1) support

### ISSUE THREAD

**Issue by TimonPeng** [nabla-c0d3/ssl-kill-switch2#17]

**Comment by LiboDing** [comment]
seems not work in iOS 10.1.1

**Comment by LiboDing** [comment]
Install all packages, reboot SpringBoard, kill itunesstored process, and open App Store, I got messages(related with SSLKillSiwtch2) as below:
SandboxViolation: AppStore(1498) deny(1) file-read-times /private/var/db/stash/_.RDJG0q/DynamicLibraries/SSLKillSwitch2.dylib
Maybe not compatible with Cydia Substrate? Any ideas?

**Comment by TimonPeng** [comment]
Whats version about your Substrate etc..? @LiboDing

**Comment by LiboDing** [comment]
0.9.6301 @TimonPeng

**Comment by nabla-c0d3** [comment]
The 10.1.1 jailbreak is too unstable right now - I am waiting for a non-beta release.

**Comment by alessandro893** [comment]
10.2?

**Comment by ablewalmsley** [comment]
seconding the motion for 10.2 support, its pretty stable at this point even though its still in beta.

**Comment by nabla-c0d3** [comment]
Yep - I'll look into it this week.

**Comment by varuzhnikov** [comment]
@nabla-c0d3 could you please look into it(ios 10.2) as soon as possible. I'm ready to donate you!!!

**Comment by ChristopherHammond13** [comment]
Bumping for 10.2 support. Got a project that this would be super useful for. 

Does it work with iMessage btw?

**Comment by nabla-c0d3** [comment]
Yeah I just had a look and it does not work on 10.2 at all, which is surprising. Looks like made some big changes to the network stack. Will keep looking...

**Comment by ChristopherHammond13** [comment]
@nabla-c0d3 ah that is annoying. Is there an alternative to this method? Parts of iOS (e.g. iCloud and iMessage) seem completely impossible to MITM due to pinning.

**Comment by alessandro893** [comment]
Alternative is to create a flex patch

**Comment by nabla-c0d3** [comment]
I think I have something that works now. If confirmed I'll release a new version tomorrow.

**Comment by alessandro893** [comment]
👍 🤘

**Comment by nabla-c0d3** [comment]
It's released now: https://github.com/nabla-c0d3/ssl-kill-switch2/releases/tag/0.11
Technical details here: https://nabla-c0d3.github.io/blog/2017/02/05/ios10-ssl-kill-switch/
