### ISSUE TITLE
v0.11

### ISSUE THREAD

**Issue by alessandro893** [nabla-c0d3/ssl-kill-switch2#18]
IOS 10.2  (iPhone 6s)

Mail.app, 
youtube.app,
instagram.app,
facebook.app

didn't work. (no connection to server)

**Comment by ximerus** [comment]
Instagram 10.6 on iOS 9.3.2 working fine.

**Comment by chantysothy** [comment]
Facebook 78 on IPad Air2 IOS 10.2 is working fine
Facebook 78 on IPhone 6S IOS 10.2 is not working.

**Comment by nabla-c0d3** [comment]
Duplicate of #13
