### ISSUE TITLE
Really dirty patch 

### ISSUE THREAD

**Issue by Mila432** [nabla-c0d3/ssl-kill-switch2#19]
https://github.com/nabla-c0d3/ssl-kill-switch2/issues/17

Your patch is really dirty :) , apps like Remote Desktop , discord stop working because of the patch.

**Comment by nabla-c0d3** [comment]
Yes it is =) Surely there is a cleaner way to do this but unfortunately I can't spend too many week-ends on it. PRs are welcome tho.
