### ISSUE TITLE
A little problem

### ISSUE THREAD

**Issue by zcc1414** [nabla-c0d3/ssl-kill-switch2#21]
HI
I know iOS10 has not show the NSlog info.
I want to know how can you  print the NSLog information
Mar  3 18:01:04 iPhone XXXXX(SSLKillSwitch2.dylib)[2781] <Notice>: === SSL Kill Switch 2: Preference set to 1.
Mar  3 18:01:04 iPhone XXXXX(SSLKillSwitch2.dylib)[2781] <Notice>: === SSL Kill Switch 2: Subtrate hook enabled.

I compile the dylib 
Both print and NSlog are not show to idevicesyslog

thinks

**Comment by lgq2015** [comment]
我也是看不到日志

**Comment by alessandro893** [comment]
因為它不工作
