### ISSUE TITLE
Any progress on macOS Sierra?

### ISSUE THREAD

**Issue by masihyeganeh** [nabla-c0d3/ssl-kill-switch2#22]
I want to report that this stopped working on macOS Sierra.
Can you please investigate the problem?

Tested with macOS 10.12.4 and lldb-370.0.37.
There is no error, but it can't disable certificate pinning.

**Comment by valentinradu** [comment]
@masihyeganeh I made a pull request [here](https://github.com/nabla-c0d3/ssl-kill-switch2/pull/23). It's a simple fix for macOS Sierra, you can use it until it gets merged on the main repo.

**Comment by nabla-c0d3** [comment]
Which Apps did you try it on? I don't have any Mac App that does SSL pinning to test it out.

**Comment by masihyeganeh** [comment]
@valentinradu Thanks, I will test it now

@nabla-c0d3 I don't know, you can just test it on Mac App Store's login
