### ISSUE TITLE
[RESPONSE 500] Removed invalid header: Proxy-Connection: keep-alive

### ISSUE THREAD

**Issue by mangledbottles** [nabla-c0d3/ssl-kill-switch2#24]
Hello,
When I use SSL Kill Switch 2 on most apps it works. However, with some apps I get "Removed invalid header: Proxy-Connection: keep-alive" on some apps.

Possibly, one too many bypasses which cause the apps to fail connection?

Thanks :)

**Comment by nabla-c0d3** [comment]
I don't think this error would be related to pinning, or its bypass. Good luck!
