### ISSUE TITLE
ssl-kill-switch2 bricked iPhone6 iOS 9.1

### ISSUE THREAD

**Issue by captincook** [nabla-c0d3/ssl-kill-switch2#25]
I tried the tool on iPhone6 iOS 9.1. I followed the installation guide copied it to the device and installed. New menu appeared in the device's settings and I rebooted iPhone. Now the phone DOES NOT BOOT it just stuck displaying Apple logo.

Why didn't you mention in the readme that this tool CAN BRICK the device ?
Do you have any suggestion how to recover the device ?

**Comment by nabla-c0d3** [comment]
Unfortunately, like any tweak there is a small chance that it will crash some kind of system process and put the device in a boot loop.
Have you tried the Substrate safe mode?

https://www.theiphonewiki.com/wiki/Cydia_Substrate

**Comment by captincook** [comment]
THANK YOU very much... holding down the volume up key allowed me to continue the boot process so I was able to uninstall SSLKillSwitch. Thanks !
