### ISSUE TITLE
iOS 8

### ISSUE THREAD

**Issue by tjt263** [nabla-c0d3/ssl-kill-switch2#3]
Hey man what's the difference between this and the original one on the iSec page?
Will this one work with iOS8? The other version didn't seem to work with all my apps.

**Comment by nabla-c0d3** [comment]
Yeah this one should work. The main difference is that this one also works for OS X Apps, and also that I will maintain it when new versions of iOS gets released.

**Comment by tjt263** [comment]
ok cool, fyi: it doesn't seem to be working on ios8. i ended up having to use a dns proxy and some fake ssl certs etc instead.
