### ISSUE TITLE
Injecting DYLIB into jailed app

### ISSUE THREAD

**Issue by ninoz** [nabla-c0d3/ssl-kill-switch2#31]
Hi

Firstly thanks for your efforts on this app, its extremely helpful!

I'm using Theos-Jailed to inject your DYLIB into the "Damn Vulnerable iOS App" to bypass the Certificate pinning check within the transport security section.

I have the DYLIB loading and I could initially see that hooking was disabled due to the lack of preference file being present.  Within SSLKillSwitch.m I changed line 42 from NO to YES and according to the console the module is loading:

DamnVulnerableIOSApp(SSLKillSwitch2.dylib)[1937] <Notice>: === SSL Kill Switch 2: Subtrate hook enabled.

However the certificate pinning still seems to be in place, I am running all the traffic through Burp suite and I have the CA loaded and trusted on the device. 

Thanks for any insight you can give!

iOS: 10.3.1
iPhone 7+

**Comment by ninoz** [comment]
I just deployed the same app on a jailbroken device and it works as expected so I guess a jailbreak is required for the hooking to work :(

**Comment by nabla-c0d3** [comment]
I haven't tried myself byt It should work on a non-jailbroken  device. Make sure to build the Xcode project (not the Theos/Makefile project).

**Comment by ninoz** [comment]
Hi, Thanks for the reply.

I was building using the theos make file, just tried with the xcode project.

I'm not sure if your familiar with theos-jailed but it supports injecting in a number of different format (framework/dylib etc)

https://github.com/kabiroberai/theos-jailed/wiki/Usage

Its like a question for it's developer but which method would you recommend?

**Comment by nabla-c0d3** [comment]
I am not familiar with theos-jailed but it seems like it should work. Personally I just inject the KillSwitch the library using a load command, and re-package the full App with it.

**Comment by ninoz** [comment]
Hi

I did a little search and found a tutorial on injecting the DYLIB using otool

Within the console I get the following:
Aug 27 13:07:55 iPhoneN DamnVulnerableIOSApp(SSLKillSwitch.dylib)[3473] <Notice>: === SSL Kill Switch 2: Fishhook hook enabled.

So it looks like the injection is working as expected however its using the OS X based fishhook opposed to the substrate hook.  I have to admit I'm not entirely sure what I'm doing with it comes to objective C.  Im guessing I need to ensure that the preprocessing directive is set to being  SUBSTRATE_BUILD?
