### ISSUE TITLE
seems not work against app store on ios10.2 use iphone

### ISSUE THREAD

**Issue by dengtongtongtong** [nabla-c0d3/ssl-kill-switch2#34]
I have followed the instruction. First load SSLKillSwitch2, to finger out whether this is success. I print out syslog and see /Library/MobileSubstrate/DynamicLibraries/SSLKillSwitch2.dylib message. Secondly I kill both appstored and itunestored. Finally I still can not catch the traffic of apple store, any suggestion about this?

**Comment by dengtongtongtong** [comment]
Fixed

**Comment by inputfuture** [comment]
@dengtongtongtong  same error here,how did you fix it ?thank you.
