### ISSUE TITLE
dlopen fails with 0 return value

### ISSUE THREAD

**Issue by an0** [nabla-c0d3/ssl-kill-switch2#35]
I'm trying it on macOS 10.13.1 with lldb-900.0.61:

1. `lldb app path`
2. `break set -n NSApplicationMain`
3. `run`
4. expr (void*)dlopen("/Users/an0/Library/Developer/Xcode/DerivedData/SSLKillSwitch-xxxj/Build/Products/Debug/SSLKillSwitch.framework/SSLKillSwitch", 1)

But I got `(void *) $1 = 0x0000000000000000`. What did I do wrong?

**Comment by malhal** [comment]
Enable code-signing, build for profiling, copy from the Release folder to the app's Resources. I added these instructions to the readme #38

**Comment by nabla-c0d3** [comment]
Thanks again =)
