### ISSUE TITLE
Does not work on IOS 10.3.2

### ISSUE THREAD

**Issue by MTester2018** [nabla-c0d3/ssl-kill-switch2#41]
Hi,
the last relatese 0.11 does not bypass ssl pinning on iOS 10.3.2 !
Does any one test it on this iOS version? do you have any idea/suggestion?

Thanks!
MAL

**Comment by nerozhao** [comment]
I tested, it work, you should kill the process

**Comment by nabla-c0d3** [comment]
It works on iOS 11 now - support for 10.3.2 (assuming it doesn't work) is not on the roadmap.
