### ISSUE TITLE
macOS High Sierra Support

### ISSUE THREAD

**Issue by arturdev** [nabla-c0d3/ssl-kill-switch2#45]
I'm trying to inject sslkillswitch into mac's AppStore app but I'm still getting error on sign-in while proxying.

<img src="https://i.imgur.com/28LWdr5r.jpg">

Dylib is injected to process successfully: 
<img src="https://i.imgur.com/4rUW91o.png">

Is there any other process that should be injected, or that's a bug?

**Comment by sharifulin** [comment]
@arturdev Hi, did you find a solution?

**Comment by arturdev** [comment]
@sharifulin , unfortunately :(

**Comment by Mila432** [comment]
all i can say its not the itunes process , you have to inject it into a daemon

**Comment by espresso-flavoured** [comment]
Perhaps it's _akd_ (AuthKit). I haven't tried that myself yet, though.

**Comment by AppleTechy** [comment]
Is anyone else having issues with Macos Mojave? I keep getting an error that expr is an unexpected token. `MacBook-Pro:~ AppleGeek$ dlopen()
>  (lldb) expr (void*)dlopen("/Users/AppleGeek/Library/Developer/Xcode/DerivedData/SSLKillSwitch-ecynccfqxmngiydaoeymeyawohbq/Build/Products/Debug/SSLKillSwitch.framework/Versions/A/SSLKillSwitch", 1)
-bash: syntax error near unexpected token `expr'
MacBook-Pro:~ AppleGeek$ dlopen()
> (lldb) expr (void*)dlopen("/Users/AppleGeek/Library/Developer/Xcode/DerivedData/SSLKillSwitch-ecynccfqxmngiydaoeymeyawohbq/Build/Products/Debug/SSLKillSwitch.framework/Versions/A/SSLKillSwitch", 1)
-bash: syntax error near unexpected token `expr'`

**Comment by AppleTechy** [comment]
Unfortunately I seem to be running into a similar issue on Mojave. Where is keeps returning a 0 pointer value.
