### ISSUE TITLE
iOS 9 compatibility (booting problem)

### ISSUE THREAD

**Issue by danylokostyshyn** [nabla-c0d3/ssl-kill-switch2#5]
Hi, sorry for bothering, but could you please help me, or just point me in to the right direction, i used  [ios-ssl-kill-switch](https://github.com/iSECPartners/ios-ssl-kill-switch) (iSECPartners) on iOS 8 and previous, on iOS 9 it works, but it prevents a phone (4s, armv7, 9.0.2) from booting, so i can install it and use it, but i can't reboot the phone with the tweak installed, i think it might be related to [this](https://twitter.com/saurik/status/654198997024796672) (sauriks'  tweet), so i want to try to build [ssl-kill-switch2](https://github.com/nabla-c0d3/ssl-kill-switch2) with those settings enabled, but unfortunately i can't, here is an [error log](http://pastebin.com/qwhpspqY) which i gets, thanks!

**Comment by nabla-c0d3** [comment]
Hi,
Your build environment seems to have issues... have you been able to compile a tweak before? I re-compiled the tweak with Saurik's fix but haven't tested anything - feel free to try the tentative-ios9 package I just uploaded https://github.com/nabla-c0d3/ssl-kill-switch2/releases

**Comment by danylokostyshyn** [comment]
hi, thanks a lot!  no i never tried to compile a tweak my self but i followed the instruction how to setup environment from [here](http://iphonedevwiki.net/index.php/Theos/Setup), probably i made a mistake somewhere, i will try to do it one more time later. Thanks for compiling it for me, unfortunately issue still present, the tweak works, but i can't reboot the phone with it installed, maybe something changed in MobileSubstrate on iOS 9, i don't know, anyway thanks for your help

**Comment by markus0m** [comment]
I tried the old (package) version and got the boot problem. 
Just found v2 and will give it a try. Thumbs up!

Doesn't seem like anything was uploaded though - the release is still at 0.7
Did I just miss it somehow?

**Comment by nabla-c0d3** [comment]
I removed it as @danylokostyshyn said it wasn't working.

I will re-compile SSL Kill Switch for iOS 9 once people have figured out what the issue is and how to fix it (http://www.iphonedevwiki.net/index.php/Updating_extensions_for_iOS_9).

**Comment by markus0m** [comment]
I see! Not functional or just not solving the reboot issue?
If you have a new version for testing, just let us know on here.
I'm on an iPhone 5s.

**Comment by nabla-c0d3** [comment]
Have you tried the iOS 8 version ? it should work the same on iOS 9 (except for the reboot issue on 32 bits devices).

**Comment by Hope4hope** [comment]
Same problem, using iPad 2, with 9.0.2, installed your released deb, after reboot device is dead.

**Comment by markus0m** [comment]
Hold the volume up key while hard resetting. 
Safe mode will fail but you should be able to boot eventually and remove the patch.

**Comment by danylokostyshyn** [comment]
it isn't dead actually, you can always boot the device in a safe mode (hold the volume down key when apple logo appears) and uninstall the tweak, currently i'm using next wolkaround myself:

because the tweak actually works OK, the only problem is in loading it while the boot stage
i've built the .dylib separately ([small script](https://gist.github.com/danylokostyshyn/c8f68cfa700e707fc11f))
and when i need to disable ssl, i just copy the dylib to `/Library/MobileSubstrate/DynamicLibraries/` and re-spring the phone (`killall -HUD SpringBoard`), when it's no longer needed i just remove it form DynamicLibraries folder

**Comment by Hope4hope** [comment]
nabla-c0d3, Also if possible add SSLKillSwitch.framework into git

**Comment by Hope4hope** [comment]
danylokostyshyn, thank you for your solution, you are the best

**Comment by magicguru** [comment]
Can anybody get this working for iOS 9 without having to activate it after booting?

**Comment by nabla-c0d3** [comment]
I just released v0.8 - please try it and re-open the issue if it doesn't work. On my iPhone 4S it seems to work fine with no boot loop.

**Comment by danylokostyshyn** [comment]
thanks! works great again! such a simple fix :) how did you find this out?

**Comment by DonTim** [comment]
Works great with my iPhone 6s and iOS 9
Could you try to update introspy for iOS aswell?
Thanks

**Comment by nabla-c0d3** [comment]
Good to know - regarding Introspy I don't have time to maintain it : /

**Comment by markus0m** [comment]
5s boots as well, thanks!
