### ISSUE TITLE
Not working on iOS 11.3.1

### ISSUE THREAD

**Issue by XMB5** [nabla-c0d3/ssl-kill-switch2#50]
Each process logs that SSL Kill Switch has been enabled, but nothing more happens.

**Comment by general7078** [comment]
Me too. I want to see the traffic detail about App Store, it works fine in earlier iOS editions, but not in iOS 11.3.1, which is jailbroken recently.

**Comment by whoot** [comment]
+1 Does also not work on iOS 11.1.2. Even the new menu in the device's setting is not shown.

**Comment by r3ggi** [comment]
+1, not working on iOS 11.3.1. Killswitch logs that is successfully injected but nothing more happens + it's not visible in the settings

**Comment by r3ggi** [comment]
I found a solution:
1. I unjailbroke my iPhone using Rollectra 
2. Then installed unc0ver in the newest version (make sure that Load Tweaks option in enabled)
3. Manually installed killswitch using dpkg -i

**Comment by yoimhere** [comment]
> I found a solution:
> 
> 1. I unjailbroke my iPhone using Rollectra
> 2. Then installed unc0ver in the newest version (make sure that Load Tweaks option in enabled)
> 3. Manually installed killswitch using dpkg -i

not working

**Comment by r3ggi** [comment]
Interesting, in my case it worked. 

On Electra JB there is one external tool need to be installed - PreferenceLoader - http://www.3u.com/news/articles/5951/preferenceloader-brings-settings-for-each-and-every-installed-cydia-tweak

**Comment by chrisbog94** [comment]
@yoimhere @r3ggi 
Try this...

Go to Settings -> General -> About

Go all the way to the bottom and click "Certificate Trust Settings" and turn on your certificate from Charles, mitmproxy, burp, etc.

**Comment by yoimhere** [comment]
> I found a solution:
> 
> 1. I unjailbroke my iPhone using Rollectra
> 2. Then installed unc0ver in the newest version (make sure that Load Tweaks option in enabled)
> 3. Manually installed killswitch using dpkg -i



> @yoimhere @r3ggi
> Try this...
> 
> Go to Settings -> General -> About
> 
> Go all the way to the bottom and click "Certificate Trust Settings" and turn on your certificate from Charles, mitmproxy, burp, etc.
> 
> > Feel free to buy me a beer if it worked!

i done, but not work. console logs that "SSL Kill Switch has been enabled" too

**Comment by yoimhere** [comment]
> Interesting, in my case it worked.
> 
> On Electra JB there is one external tool need to be installed - PreferenceLoader - http://www.3u.com/news/articles/5951/preferenceloader-brings-settings-for-each-and-every-installed-cydia-tweak

maybe some apps work and some fail. many tks.
