### ISSUE TITLE
Ineffective with Appcelerator SSL Pinning

### ISSUE THREAD

**Issue by aph3rson** [nabla-c0d3/ssl-kill-switch2#57]
I've posted this as sensepost/objection#187, but it might be useful here as well.

Apps using Appcelerator by Axway have a customized SSL verification library. This uses an SSL certificate bundled with the app, a custom verification method, and is not affected by SSL Kill Switch. This can be fixed in Objection by patching `-[AppceleratorHttpsModule createX509CertificatePinningSecurityManager:]` to always return null - passing a null value as the address of the security manager causes SSL pinning to be disabled.

**Comment by nabla-c0d3** [comment]
Thanks for the heads up. The new version that works for iOS 12 should handle this.
