### ISSUE TITLE
iOS 12 support

### ISSUE THREAD

**Issue by trerter** [nabla-c0d3/ssl-kill-switch2#58]
Please, rebuild for ios 12
thanks

**Comment by qunuan** [comment]
```
Please, rebuild for ios 12
thanks
```

**Comment by lbbniu** [comment]
Please, rebuild for ios 12
thanks

**Comment by zj1842** [comment]
please, rebuild for ios 12, thanks, we need this.

**Comment by stypr** [comment]
Please, rebuild for ios 12
thanks

**Comment by caoxiangyu666** [comment]
Please, rebuild for ios 12
thanks

**Comment by jonluca** [comment]
I've rebuilt a version for iOS 12. It is exactly the same as `HEAD` on this repo, so I'm not sure if anything has actually changed.

I've hosted it on the Cydia repo `https://jonlu.ca/repo/`.

**Comment by thierbig** [comment]
Hey ! Please rebuild for ios 12 :)

**Comment by dhogberg** [comment]
Pleaseee, iOS 12. Thank you!

**Comment by nabla-c0d3** [comment]
Duplicate of #55
