### ISSUE TITLE
Build environment details

### ISSUE THREAD

**Issue by radj** [nabla-c0d3/ssl-kill-switch2#6]
I am trying out this repo with RPetrich's [theos](https://github.com/rpetrich/theos) but encountering this build error which is weird. 

    Undefined symbols for architecture armv7:
        "_MSHookFunction", referenced
             _init in SSLKillSwitch.m.45a1eea5.o

That function should be pretty basic in tweaks so I guess I have my build environment misconfigured or something. What tools are you using right now to build this project successfully?

This is my environment:
* OS X 10.9.5
* XCode 6.2 + CLI Tools
* RPetrich's [theos](https://github.com/rpetrich/theos)
* env SDKVERSION=8.2
* I forgot already where I got my `theos/includes`. Might be outdated? Where do you guys get yours?

Might help to note that the current build environment I have works fine with Introspy and builds successfully.

**Comment by danylokostyshyn** [comment]
RPetrich's theos doesn't include CydiaSubstrate by default
Add this line to Makefile
SSLKillSwitch2_LIBRARIES = substrate

**Comment by radj** [comment]
@danylokostyshyn That was all that it needed! I now know what to do when this issue occurs again with other projects. Thanks. By the way, which theos version are you using?

**Comment by danylokostyshyn** [comment]
And make sure you are using latest CydiaSubstrate version, you can find it in a [saurik's repo](http://apt.saurik.com/debs/)
RPetrich's one as well
