### ISSUE TITLE
part of AppStore iOS12 traffic is not working

### ISSUE THREAD

**Issue by liuxuan30** [nabla-c0d3/ssl-kill-switch2#64]
So I installed the tweak for iOS12. While checking the app store traffic, most of them are working, but I found when signing in, domains like init.itunes.apple.com and buy.itunes.apple.com is not working, saying handshake failed.

I tried to look into boringssl other functions, but seems nothing suspicious. I wanted to help, so can someone help to give some ideas so I could try out?

**Comment by imHugoDev** [comment]
How did you get it to open apps on iOS 12? Im on 12.0.1 [iPhone XS Max] and all my apps crash after enabling the tweak and respringing.

Thanks.

**Comment by liuxuan30** [comment]
@imHugoDev don't hijack my thread for other issues. and yes it's fine on my side, everything is ok. just follow README

**Comment by imHugoDev** [comment]
@liuxuan30 Not hijacking your thread, just asking how you managed to get it to work. Alright?

**Comment by liuxuan30** [comment]
just installed and works as usual. nothing special.

**Comment by Yui550** [comment]
> So I installed the tweak for iOS12. While checking the app store traffic, most of them are working, but I found when signing in, domains like init.itunes.apple.com and buy.itunes.apple.com is not working, saying handshake failed.

I have the same problem now, is there a way to solve it?

**Comment by MichaelKostin** [comment]
Hi @liuxuan30. Did you solve the issue?
