### ISSUE TITLE
SSL Handshake error in iOS 9.0.2

### ISSUE THREAD

**Issue by Hope4hope** [nabla-c0d3/ssl-kill-switch2#7]
I'm using Burp, iOS 9.0.2, when accessing Safari any website with https say that: 
![Verify Server Identity](https://cloud.githubusercontent.com/assets/15231625/10820426/d5cef636-7e55-11e5-8381-4eb7eb037ba1.jpg)
After installing custom certificate SSL, everything works well
BUT
When downloading from Appstore have that error:
![screen shot ](https://cloud.githubusercontent.com/assets/15231625/10820276/062cfc16-7e55-11e5-948f-27ffd1ebcb10.png)
Is any system protection in iOS 9 for checking the trusted ssl? because on iOS 8.4 everything works as it should.
With iOS 9.0.2 many apps not working if using ssl-kill-switch, like Facebook, Appstore

How to avoid that situation? Maybe I'm doing something not correctly?

**Comment by Hope4hope** [comment]
Also com.nablac0d3.SSLKillSwitch2_0.8.deb, not solved that problem :(

Also nabla-c0d3 update version in Preference  SHOULD BE—>   SSL Kill Switch 2  v0.8


![screen shot 2015-10-29 at 16 08 09](https://cloud.githubusercontent.com/assets/15231625/10820728/6e25961e-7e57-11e5-9c33-1702e0c2bc1f.png)

**Comment by Hope4hope** [comment]
Maybe Apple verify certificates with that list?
https://support.apple.com/en-md/HT205205

**Comment by nabla-c0d3** [comment]
I just removed the version from the preference bundle. For proxy-ing the App Store things are different; please read the README as it has link to the instructions.

**Comment by nabla-c0d3** [comment]
And also, make sure you restart the Apps after having enabled SSL Kill Switch.
