### ISSUE TITLE
Not working with Checkra1n jailbreak on iOS 13

### ISSUE THREAD

**Issue by MuchiMuchiPink** [nabla-c0d3/ssl-kill-switch2#71]
Device: iPhone 7
OS: iOS 13.1
JB: Checkra1n beta 0.9.1

Once an app is hooked with SSLKillSwitch, all apps crash until the tweak is removed.

**Comment by rubobaquero** [comment]
I have the same problem.

Device: iPhone 7
OS: iOS 13.2.2
JB: Checkra1n beta 0.9.2

**Comment by tmm1** [comment]
Same with checkra1n beta 0.9.3

**Comment by anaseqal** [comment]
Hi, until @nabla-c0d3 release next update, try this one and let me know if it works for you so i can share the code

[com.nablac0d3.sslkillswitch2_0.13-16+debug_iphoneos-arm.deb](https://anaseqal.com/com.nablac0d3.sslkillswitch2_0.13-16+debug_iphoneos-arm.deb)

for me it works well on ios13:
![SSL KillSwitch iOS13](https://anaseqal.com/sslkillswitch.png)

**Comment by hosijyun** [comment]
I think it is the bug of substrate or Checkra1n.
The exception type is EXC_BAD_INSTRUCTION. When I look at the crash site the instruction is "LDR X8, [X0,#8]" which is the first instruction of function "SSL_set_custom_verify". The substrate will replace this instruction for hooking and cause the exception. You may use fishhook instead.

**Comment by Mitsj0l** [comment]
> Hi, until @nabla-c0d3 release next update, try this one and let me know if it works for you so i can share the code
> 
> [com.nablac0d3.sslkillswitch2_0.13-16+debug_iphoneos-arm.deb](https://anaseqal.com/com.nablac0d3.sslkillswitch2_0.13-16+debug_iphoneos-arm.deb)
> 
> for me it works well on ios13:
> ![SSL KillSwitch iOS13](https://camo.githubusercontent.com/00e7679267df9c1ad347b7959ebbe65be24c7958/68747470733a2f2f616e61736571616c2e636f6d2f73736c6b696c6c7377697463682e706e67)

This sir, works like a charm!

**Comment by bravery9** [comment]
> Hi, until @nabla-c0d3 release next update, try this one and let me know if it works for you so i can share the code
> 
> [com.nablac0d3.sslkillswitch2_0.13-16+debug_iphoneos-arm.deb](https://anaseqal.com/com.nablac0d3.sslkillswitch2_0.13-16+debug_iphoneos-arm.deb)
> 
> for me it works well on ios13:
> ![SSL KillSwitch iOS13](https://camo.githubusercontent.com/00e7679267df9c1ad347b7959ebbe65be24c7958/68747470733a2f2f616e61736571616c2e636f6d2f73736c6b696c6c7377697463682e706e67)

Thank you very much!!!
It work for me.
Love you :D

**Comment by tmm1** [comment]
> so i can share the code

Looking forward to seeing the PR for iOS 13 support

**Comment by anaseqal** [comment]
> > so i can share the code
> 
> Looking forward to seeing the PR for iOS 13 support

https://github.com/nabla-c0d3/ssl-kill-switch2/pull/72

**Comment by MuchiMuchiPink** [comment]
@anaseqal thanks a lot! For now my frida-scripts still work :) But I can't test your deb because I'm on vacation right now, but close this anyways seeing it does for others.

**Comment by nabla-c0d3** [comment]
I will leave this open until I’ve made an “official” release. Until then it sounds like @anaseqal ’s PR will work fine.

**Comment by frankl1m** [comment]
Is working pretty good, i have another ask is posible make a version that after install in system from whatever way. will be enabled auto in system without had to Switch On in Settings, asuming all risks of curse, thanks you anyways

> > > so i can share the code
> > 
> > 
> > Looking forward to seeing the PR for iOS 13 support
> 
> #72

**Comment by Merkie** [comment]
> Hi, until @nabla-c0d3 release next update, try this one and let me know if it works for you so i can share the code
> 
> [com.nablac0d3.sslkillswitch2_0.13-16+debug_iphoneos-arm.deb](https://anaseqal.com/com.nablac0d3.sslkillswitch2_0.13-16+debug_iphoneos-arm.deb)
> 
> for me it works well on ios13:
> ![SSL KillSwitch iOS13](https://camo.githubusercontent.com/00e7679267df9c1ad347b7959ebbe65be24c7958/68747470733a2f2f616e61736571616c2e636f6d2f73736c6b696c6c7377697463682e706e67)

doesn't show up in prefs for me :(

**Comment by nabla-c0d3** [comment]
Released as part of v0.14. Thanks for the help!

**Comment by samuelscheit** [comment]
How do I remove the tweak, sadly I don't have SSH access

**Comment by OsamaMahmood** [comment]
not working on 13.6.1 jb using checkrain

**Comment by samuelscheit** [comment]
> How do I remove the tweak, sadly I don't have SSH access

You need to turn off WLAN and turn on Flight Mode

**Comment by OsamaMahmood** [comment]
> > How do I remove the tweak, sadly I don't have SSH access
> 
> You need to turn off WLAN and turn on Flight Mode

Did you got it working on iOS 13.6.1 because when i proxy the traffic apps having ssl pining enabled keeps on crashing
