### ISSUE TITLE
Doesn't work on cloudd

### ISSUE THREAD

**Issue by anonymouz4** [nabla-c0d3/ssl-kill-switch2#78]
I successfully loaded the signed framework into the cloudd process, returned a non-null pointer, so success.
But SSL pinning is still active. Either the method the process uses isn't hooked, the hooking doesn't work. I verified that the framework launch code is being executed

**Comment by nabla-c0d3** [comment]
Can you describe in more details how you loaded the framework so I can reproduce it ? Thanks!

**Comment by anonymouz4** [comment]
There are multiple ways, but the simplest is to attach a debugger like lldb and run `expr dlopen("<path_to_executable>",1)`

I don't think it's bug, just that this application uses its own ssl pinning methods, not defaults like in your code.

For example a similar process like `akd`(which uses the AuthKit framework) has it's own ssl pinning method:  `@class AKCertificatePinning 
+(BOOL)isValidCertificateTrust:id forHostname:id`
