### ISSUE TITLE
Not working with unc0ver + iOS 13.5 XS

### ISSUE THREAD

**Issue by sooxt98** [nabla-c0d3/ssl-kill-switch2#87]
I did enable, the interceptor still showing ssl

![image](https://user-images.githubusercontent.com/13378059/82847904-48aa1800-9f23-11ea-95ee-d4b4397dc5c5.jpeg)

**Comment by Eat-Sleep-Code-fun** [comment]
I am getting the same problem. You the lucky ones, you can at least see the SSL kill SWitch tab in your phone. For me, No SSL kill switch tab in settings :(.

**Comment by yywoxin** [comment]
Not working with unc0ver + iOS 13.5 ipone6s too

**Comment by yywoxin** [comment]
> Not working with unc0ver + iOS 13.5 ipone6s too

this problem is solved, restart the application

**Comment by holyswordman** [comment]
> 
> 
> > Not working with unc0ver + iOS 13.5 ipone6s too
> 
> this problem is solved, restart the application

so it works with iPhone 6s unc0ver + iOS 13.5, isn't?

**Comment by bamhm182** [comment]
I'm also having no luck on the iPhone SE 2 (2020) on 13.5, jailbroken with unc0ver 5.0.1. I have configured Burp Suite to intercept network requests and can see requests to 'http://neverssl.com' just fine, however, requests to 'https://www.google.com' fail with "Safari cannot open the page because it could not establish a secure connection to the server."

**Comment by profiles** [comment]
maybe a arm64e support issue, compile the newest code

**Comment by JulyIghor** [comment]
works fine for me on iOS 13.5 iPhone SE 2016

**Comment by 4val0v** [comment]
**Not working**
iPhone SE, **iOS 13.7** - checkra1n
_App Store - Cannot Connect to App Store_

**Comment by JulyIghor** [comment]
> **Not working**
> iPhone SE, **iOS 13.7** - checkra1n
> _App Store - Cannot Connect to App Store_

have you killed itunesstored process?

**Comment by 4val0v** [comment]
> have you killed itunesstored process?

Yes
```bash
ps -ef | grep itunesstored
kill -s KILL 183
```

**Comment by 4val0v** [comment]
@JulyIghor You said that works for you, what version of Java and Burp are you using?

_I have such a situation:_
1) Burp 2020.4 + Java 13 + My SSL Certificate = Not work
2) Burp 2.1.07 with Portswigger SSL (Default) + Java 8 = Fine works

**Comment by JulyIghor** [comment]
> @JulyIghor You said that works for you, what version of Java and Burp are you using?
> 
> _I have such a situation:_
> 
> 1. Burp 2020.4 + Java 13 + My SSL Certificate = Not work
> 2. Burp 2.1.07 with Portswigger SSL (Default) + Java 8 = Fine works

Fiddler
