### ISSUE TITLE
Downloading fails when proxying and downloading an app

### ISSUE THREAD

**Issue by trueicecold** [nabla-c0d3/ssl-kill-switch2#9]
I've tried fiddler and charles proxy to sniff the download process of an app from the appstore on iOS (8.1.3). Used KillSwitch 0.8 for that. Everything works perfectly fine (Awesome job!) except downloading an app.

Clicking on "GET" and "INSTALL", the request is rejected, and the button goes back to "GET".

Any ideas?

**Comment by nabla-c0d3** [comment]
Did you look at this https://github.com/nabla-c0d3/ssl-kill-switch2/issues/8 ?

**Comment by nabla-c0d3** [comment]
It should work fine in 0.9

**Comment by trueicecold** [comment]
I'm unable to get it to inject killswitch when killing itunesstored.

Device logs once I kill the process are:

```
com.apple.xpc.launchd[1] (com.apple.itunesstored[913]) <Notice>: Service exited due to signal: Killed: 9
itunesstored[921] <Notice>: MS:Notice: Injecting: com.apple.itunesstored [itunesstored] (1144.17)
itunesstored[921] <Notice>: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/Veency.dylib
itunesstored[921] <Notice>: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/hidspringboard.dylib
itunesstored[921] <Notice>: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/libstatusbar.dylib
itunesstored[921] <Notice>: CoreFoundation = 1144.170000
```

**Comment by trueicecold** [comment]
I'm lost here...

I've checked the filter, even by extracting the deb file, and inside:

data\Library\MobileSubstrate\DynamicLibraries

I see the plist which has the 2 filters:

```
{
	Filter = {
		Bundles = (
			"com.apple.AuthKit",
			"com.apple.UIKit",
		);
	};
}
```

And yet, killing itunesstored doesn't inject KillSwitch2 into it... :(

**Comment by gluckMu** [comment]
I have met the same problem. All requests are tracked, but only init.itunes.apple.com is failed.
I have used v0.9, and killed itunesstored. 
Device Log are:   
Jan 26 18:12:20 iPhone com.apple.xpc.launchd[1] (com.apple.itunesstored[775]) <Notice>: Service exited due to signal: Killed: 9
Jan 26 18:12:20 iPhone itunesstored[825] <Notice>: MS:Notice: Injecting: com.apple.itunesstored [itunesstored] (1144.17)
Jan 26 18:12:20 iPhone CLTM[124] <Error>: CLTM: _subscription 0x0, _subscribedChannels 0x0

Any suggestions?   iPhone 6  ios 8.3

**Comment by nabla-c0d3** [comment]
Try adding com.apple.itunesstored to the bundle filter ? You will then have to rebuild the tweak (`make package` and `make install`)

**Comment by gluckMu** [comment]
@nabla-c0d3  Great!!!  I have solved this problem by adding com.apple.itunesstored to the bundle filter. 
Many thanks!!!

**Comment by trueicecold** [comment]
nabla, Thanks a lot, I thought the 2 filters should have been enough! :)
so, do I just download the source code, and run those command on the terminal, and I should get a .deb file in return?

**Comment by trueicecold** [comment]
After 2 hours of tinkering with it, it's working perfect! :)
Thanks a lot!
