### ISSUE TITLE
iOS 14 cannot be installed

### ISSUE THREAD

**Issue by ghost** [nabla-c0d3/ssl-kill-switch2#90]
**iPhone:~ root#** dpkg -i com.nablac0d3.sslkillswitch2_0.14.deb
(Reading database ... 1768 files and directories currently installed.)
Preparing to unpack com.nablac0d3.sslkillswitch2_0.14.deb ...
Unpacking com.nablac0d3.sslkillswitch2 (0.14-3+debug) over (0.14-3+debug) ...
dpkg: dependency problems prevent configuration of com.nablac0d3.sslkillswitch2:
 com.nablac0d3.sslkillswitch2 depends on mobilesubstrate; however:
  Package mobilesubstrate is not installed.
 com.nablac0d3.sslkillswitch2 depends on preferenceloader; however:
  Package preferenceloader is not installed.

dpkg: error processing package com.nablac0d3.sslkillswitch2 (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 com.nablac0d3.sslkillswitch2
**iPhone:~ root#**

**Comment by asad0x01** [comment]
You'll have to install mobilesubstrate and preferenceloader from cydia.

**Comment by ghost** [comment]
ok,thinks

asad0x01 <notifications@github.com> 于2020年9月24日周四 下午4:47写道：
