### ISSUE TITLE
Does this work on iPad Pro 2020 on iOS 13.5?

### ISSUE THREAD

**Issue by hackingtosh** [nabla-c0d3/ssl-kill-switch2#94]
Does it work on the iPad Pro 2020 11 inch 2nd gen, jailbreaked with unc0ver 5.3.1 on iOS 13.5? 

Because I read that Cydia Substrate shouldn't be installed on A12 devices: https://www.reddit.com/r/jailbreak/comments/eqcyny/question_should_i_install_cydia_substrate/

**Comment by asad0x01** [comment]
Use Frida instead.
