### ISSUE TITLE
iOS 14.3 Support?

### ISSUE THREAD

**Issue by ghost** [nabla-c0d3/ssl-kill-switch2#98]
As it currently stands, ssl kill switch 2 doesn't work for ios 14.3 iphone 8 devices.

**Comment by ghost** [comment]
So far I was able to get the SSL Kill Switch to show up on my phone. Now I just need to actually test it to determine if it will work or not.

**Comment by ghost** [comment]
I don't believe that ssl kill switch works while activated. I tried to install a couple of different ipas and I got the following error below 

![image](https://user-images.githubusercontent.com/23001248/113082487-90837680-91a8-11eb-93e7-87a8bd7d643e.jpeg)

**Comment by michalRajcan** [comment]
Have you tried installing "Substitute" package in Cydia instead of the "Cydia Substrate"?
worked for me like charm.

Truth be told, I used it only to strip SSL...

offtopic: why not use Sideloadly from Pangu to install IPAs?

**Comment by iangcarroll** [comment]
FWIW: Works for me out of the box on 14.5.1 with just Cydia Substrate.

**Comment by 1trackprojects1** [comment]
> FWIW: Works for me out of the box on 14.5.1 with just Cydia Substrate.

which .deb did you use?

**Comment by pentestaec** [comment]
Could please somebody write the correct method how to install Killswitch on iOS 14.4+?

**Comment by kpratik9** [comment]
Worked for me. (Jailbroken iPhone 6s. iOS 14.5)

Open Cydia and install wget.

Ssh in to your jailbroken device and download the package in /tmp folder from the following link using wget command:

https://github.com/nabla-c0d3/ssl-kill-switch2/releases/tag/0.14

iPhone:/tmp root# wget https://github.com/nabla-c0d3/ssl-kill-switch2/releases/download/0.14/com.nablac0d3.sslkillswitch2_0.14.deb

iPhone:/tmp root# dpkg -i com.nablac0d3.sslkillswitch2_0.14.deb

If you get an error then fire the following command:

iPhone:/tmp root# apt --fix-broken install

iPhone:/tmp root# dpkg -i com.nablac0d3.sslkillswitch2_0.14.deb

Now respring your iDevice:

iPhone:~ root# killall -9 backboardd

and you are done.

Now open iOS settings app, scroll down and locate SSL Kill Switch 2. Open it and enable "Disable Certificate Validation"

Thats it.

**Comment by ptrkstr** [comment]
These instructions worked for me on iPhone 7, iOS 14.6. Thank you @kpratik9

**Comment by kpratik9** [comment]
> These instructions worked for me on iPhone 7, iOS 14.6. Thank you @kpratik9

You are welcome @ptrkstr

**Comment by Nigel1992** [comment]
Can confirm its working but make sure you respring your device after installing.

**Comment by jonluca** [comment]
This has been hosted at https://jonlu.ca/repo/ if you don't want to install this via the terminal/`dpkg` as well

**Comment by Computershik73** [comment]
Does it work on iOS 14.7? iPhone 7. I am going to buy it.

**Comment by kpratik9** [comment]
Yes. It worked for me on iOS 14.8 iPhone 7 Plus.

**Comment by Computershik73** [comment]
> Yes. It worked for me on iOS 14.8 iPhone 7 Plus.
I hope it will work with unc0ver and that I will not have to recompile it.
